CREATE SCHEMA auth;
CREATE SCHEMA atlas;
CREATE SCHEMA pulsify;

CREATE TABLE auth.users (
    id            uuid PRIMARY KEY,
    name          text NOT NULL,
    email         text NOT NULL UNIQUE,
    email_verified boolean NOT NULL DEFAULT false,
    image         text,
    role          text,
    banned        boolean NOT NULL DEFAULT false,
    ban_reason    text,
    ban_expires   timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE auth.sessions (
    id              uuid PRIMARY KEY,
    user_id         uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    token_hash      bytea NOT NULL UNIQUE,
    expires_at      timestamptz NOT NULL,
    ip_address      text,
    user_agent      text,
    impersonated_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX sessions_user_id_idx ON auth.sessions (user_id);
CREATE INDEX sessions_expires_at_idx ON auth.sessions (expires_at);

CREATE TABLE auth.accounts (
    id                       uuid PRIMARY KEY,
    user_id                  uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    provider_id              text NOT NULL,
    account_id               text NOT NULL,
    access_token             text,
    refresh_token            text,
    id_token                 text,
    access_token_expires_at  timestamptz,
    refresh_token_expires_at timestamptz,
    scope                    text,
    created_at               timestamptz NOT NULL DEFAULT now(),
    updated_at               timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider_id, account_id)
);

CREATE INDEX accounts_user_id_idx ON auth.accounts (user_id);

CREATE TABLE auth.verifications (
    id         uuid PRIMARY KEY,
    identifier text NOT NULL,
    value_hash bytea NOT NULL,
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX verifications_identifier_idx ON auth.verifications (identifier);
CREATE UNIQUE INDEX verifications_value_hash_idx ON auth.verifications (value_hash);

CREATE TABLE atlas.projects (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key                  text NOT NULL UNIQUE,
    name                 text NOT NULL,
    description          text,
    latest_version       text,
    experimental_version text,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE atlas.versions (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id       bigint NOT NULL REFERENCES atlas.projects (id) ON DELETE CASCADE,
    key              text NOT NULL,
    support_status   text NOT NULL DEFAULT 'SUPPORTED'
                     CHECK (support_status IN ('SUPPORTED', 'DEPRECATED', 'UNSUPPORTED')),
    java_min_version integer,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, key)
);

CREATE TABLE atlas.builds (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id   bigint NOT NULL REFERENCES atlas.versions (id) ON DELETE CASCADE,
    build_number bigint NOT NULL,
    channel      text NOT NULL DEFAULT 'STABLE' CHECK (channel IN ('ALPHA', 'BETA', 'STABLE')),
    time         timestamptz NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (version_id, build_number)
);

CREATE TABLE atlas.commits (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    build_id   bigint NOT NULL REFERENCES atlas.builds (id) ON DELETE CASCADE,
    sha        text NOT NULL,
    message    text NOT NULL,
    time       timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX commits_build_id_idx ON atlas.commits (build_id);

CREATE TABLE atlas.downloads (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    build_id   bigint NOT NULL REFERENCES atlas.builds (id) ON DELETE CASCADE,
    name       text NOT NULL,
    file_name  text NOT NULL,
    file_path  text NOT NULL,
    size       bigint NOT NULL,
    sha256     text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (build_id, name)
);

CREATE TABLE pulsify.projects (
    id          uuid PRIMARY KEY,
    owner_id    uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    name        text NOT NULL,
    slug        text NOT NULL UNIQUE,
    type        text NOT NULL CHECK (type IN ('server', 'plugin', 'mod')),
    description text,
    verified    boolean NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX projects_owner_id_idx ON pulsify.projects (owner_id);

-- A plugin/mod name is the only key heartbeats match installations on, so it is globally unique.
CREATE UNIQUE INDEX projects_plugin_name_key ON pulsify.projects (name)
    WHERE type IN ('plugin', 'mod');

CREATE TABLE pulsify.dsn_tokens (
    id           uuid PRIMARY KEY,
    project_id   uuid NOT NULL REFERENCES pulsify.projects (id) ON DELETE CASCADE,
    key          text NOT NULL UNIQUE,
    label        text,
    revoked      boolean NOT NULL DEFAULT false,
    last_used_at timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX dsn_tokens_project_id_idx ON pulsify.dsn_tokens (project_id);

CREATE TABLE pulsify.plugin_installations (
    plugin_id    uuid NOT NULL REFERENCES pulsify.projects (id) ON DELETE CASCADE,
    server_id    uuid NOT NULL REFERENCES pulsify.projects (id) ON DELETE CASCADE,
    version      text NOT NULL,
    enabled      boolean NOT NULL DEFAULT true,
    share_errors boolean NOT NULL DEFAULT true,
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (plugin_id, server_id)
);

CREATE INDEX plugin_installations_server_id_idx ON pulsify.plugin_installations (server_id);

CREATE TABLE pulsify.server_metadata (
    project_id   uuid PRIMARY KEY REFERENCES pulsify.projects (id) ON DELETE CASCADE,
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    software     text,
    mc_version   text,
    country_code text
);

CREATE TABLE pulsify.quotas (
    user_id            uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
    max_projects       integer NOT NULL DEFAULT 10,
    max_events_per_day bigint NOT NULL DEFAULT 100000,
    reset_at           timestamptz,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE pulsify.issues (
    id             uuid PRIMARY KEY,
    project_id     uuid NOT NULL REFERENCES pulsify.projects (id) ON DELETE CASCADE,
    fingerprint    text NOT NULL,
    plugin         text NOT NULL DEFAULT '',
    status         text NOT NULL DEFAULT 'open'
                   CHECK (status IN ('open', 'resolved', 'ignored', 'muted')),
    status_version text,
    muted_until    timestamptz,
    first_version  text,
    last_version   text,
    first_seen_at  timestamptz NOT NULL DEFAULT now(),
    last_seen_at   timestamptz NOT NULL DEFAULT now(),
    resolved_at    timestamptz,
    resolved_by    uuid REFERENCES auth.users (id) ON DELETE SET NULL,
    UNIQUE (project_id, fingerprint)
);

CREATE INDEX issues_project_status_idx ON pulsify.issues (project_id, status);

CREATE TABLE pulsify.alert_rules (
    id             uuid PRIMARY KEY,
    project_id     uuid NOT NULL REFERENCES pulsify.projects (id) ON DELETE CASCADE,
    type           text NOT NULL CHECK (type IN ('new_issue', 'regression', 'error_spike')),
    enabled        boolean NOT NULL DEFAULT true,
    threshold      integer NOT NULL DEFAULT 10 CHECK (threshold BETWEEN 1 AND 1000000),
    window_minutes integer NOT NULL DEFAULT 5 CHECK (window_minutes BETWEEN 1 AND 1440),
    webhook_url    text NOT NULL,
    last_fired_at  timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX alert_rules_project_id_idx ON pulsify.alert_rules (project_id);
CREATE INDEX alert_rules_spike_idx ON pulsify.alert_rules (type) WHERE enabled AND type = 'error_spike';

CREATE TABLE pulsify.daily_usage (
    token text NOT NULL,
    day   date NOT NULL,
    count bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (token, day)
);

CREATE INDEX daily_usage_day_idx ON pulsify.daily_usage (day);

-- Session duration is measured from `joined_at`, which is server time: the SDK's timestamp is
-- untrusted input and a Minecraft server could otherwise dictate its own session lengths.
CREATE TABLE pulsify.open_sessions (
    project_id     uuid NOT NULL REFERENCES pulsify.projects (id) ON DELETE CASCADE,
    player_uuid    uuid NOT NULL,
    joined_at      timestamptz NOT NULL DEFAULT now(),
    client_version text NOT NULL DEFAULT '',
    country_code   text NOT NULL DEFAULT '',
    PRIMARY KEY (project_id, player_uuid)
);

CREATE INDEX open_sessions_joined_at_idx ON pulsify.open_sessions (joined_at);

CREATE TABLE pulsify.ingest_queue (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   uuid NOT NULL REFERENCES pulsify.projects (id) ON DELETE CASCADE,
    payload      jsonb NOT NULL,
    received_at  timestamptz NOT NULL,
    ip           text,
    attempts     integer NOT NULL DEFAULT 0,
    available_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ingest_queue_claim_idx ON pulsify.ingest_queue (available_at, id);

CREATE TABLE pulsify.ingest_dead_letters (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  uuid NOT NULL,
    payload     jsonb NOT NULL,
    received_at timestamptz NOT NULL,
    attempts    integer NOT NULL,
    reason      text NOT NULL,
    failed_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ingest_dead_letters_failed_at_idx ON pulsify.ingest_dead_letters (failed_at);
