<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { diagnose } from '@/lib/flags/diagnose';
import type { Arch, Env, Graal, Os } from '@/lib/flags/env';
import { formatMemMB, parseMemMB } from '@/lib/flags/mem';
import { getPreset, PRESETS } from '@/lib/flags/presets';
import { batchScript, flagsOnly, type LaunchOptions, launchArgs, shellScript } from '@/lib/flags/script';
import { syncQuery } from '@/lib/query';

useHead({ title: 'JVM flags generator' });

const route = useRoute();
const query = route.query;
const asText = (key: string, fallback: string) => (typeof query[key] === 'string' ? (query[key] as string) : fallback);

const heapInput = ref(asText('heap', '6G'));
const xmsLocked = ref(asText('xms', '') === '');
const xmsInput = ref(asText('xms', '6G'));
const presetId = ref(asText('preset', 'aikar'));
const java = ref(asText('java', '21'));
const graal = ref<Graal>(asText('graal', 'none') as Graal);
const os = ref<Os>(asText('os', 'linux') as Os);
const arch = ref<Arch>(asText('arch', 'x86_64') as Arch);
const jar = ref(asText('jar', 'server.jar'));
const proxy = ref(asText('proxy', '') === '1');
const restart = ref(asText('restart', '') === '1');
const extra = ref(asText('extra', ''));

const heapMB = computed(() => parseMemMB(heapInput.value) ?? 0);
const xmsMB = computed(() => (xmsLocked.value ? heapMB.value : (parseMemMB(xmsInput.value) ?? heapMB.value)));
const heapValid = computed(() => heapMB.value > 0);

const env = computed<Env>(() => ({
  heapMB: heapMB.value,
  java: Number.parseInt(java.value, 10),
  graal: graal.value,
  os: os.value,
  arch: arch.value,
}));

const options = computed<LaunchOptions>(() => ({
  env: env.value,
  presetId: presetId.value,
  xmsMB: xmsMB.value,
  jar: jar.value.trim() || 'server.jar',
  proxy: proxy.value,
  extra: extra.value.split(/\s+/).filter(Boolean),
  restartOnExit: restart.value,
}));

const preset = computed(() => getPreset(presetId.value));
const presetFlags = computed(() => (heapValid.value ? preset.value.flags(env.value) : []));
const allArgs = computed(() => (heapValid.value ? launchArgs(options.value) : []));
const notices = computed(() => (heapValid.value ? diagnose(env.value, preset.value, presetFlags.value) : []));

const activeTab = ref('');
const tabs = computed(() => {
  const empty = 'Enter a heap size first.';
  if (!heapValid.value) {
    return [
      { id: 'sh', label: 'start.sh', filename: null, code: '', lang: 'bash' as const, empty },
      { id: 'bat', label: 'start.bat', filename: null, code: '', lang: 'batch' as const, empty },
      { id: 'flags', label: 'Flags only', filename: null, code: '', lang: 'bash' as const, empty },
    ];
  }
  return [
    { id: 'sh', label: 'start.sh', filename: 'start.sh', code: shellScript(options.value), lang: 'bash' as const },
    { id: 'bat', label: 'start.bat', filename: 'start.bat', code: batchScript(options.value), lang: 'batch' as const },
    { id: 'flags', label: 'Flags only', filename: null, code: flagsOnly(options.value), lang: 'bash' as const },
  ];
});

const optionsHint = computed(() => {
  const on = [
    !xmsLocked.value && 'split heap',
    jar.value !== 'server.jar' && 'jar name',
    proxy.value && 'proxy',
    restart.value && 'restart loop',
    extra.value.trim() && 'extra flags',
  ].filter(Boolean);
  return on.length ? `${on.length} on: ${on.join(', ')}` : 'initial heap, jar name, restart loop, extra flags';
});

/** The whole form lives in the URL so a generated set can be pasted into a support thread. */
watch(
  [heapInput, xmsLocked, xmsInput, presetId, java, graal, os, arch, jar, proxy, restart, extra],
  () => {
    syncQuery({
      heap: heapInput.value,
      xms: xmsLocked.value ? undefined : xmsInput.value,
      preset: presetId.value,
      java: java.value,
      graal: graal.value === 'none' ? undefined : graal.value,
      os: os.value,
      arch: arch.value,
      jar: jar.value === 'server.jar' ? undefined : jar.value,
      proxy: proxy.value ? '1' : undefined,
      restart: restart.value ? '1' : undefined,
      extra: extra.value || undefined,
    });
  },
  { flush: 'post' },
);

const HEAP_STEPS = ['2G', '4G', '6G', '8G', '12G', '16G', '24G', '32G'];
</script>

<template>
	<ToolsToolPage
		title="JVM flags generator"
		lead="Pick a flag set, say what the host is, and get a start script that only contains options your JVM will actually accept. The sets are the ones irori ships, generated by the same code."
	>
		<section class="setup">
			<div class="choice" role="radiogroup" aria-label="Flag set">
				<button
					v-for="option in PRESETS"
					:key="option.id"
					type="button"
					role="radio"
					:aria-checked="presetId === option.id"
					class="choice-btn"
					:class="{ on: presetId === option.id }"
					@click="presetId = option.id"
				>
					{{ option.name }}
				</button>
			</div>
			<p class="choice-sum">
				{{ preset.summary }}
				<a v-if="preset.url" :href="preset.url" target="_blank" rel="noopener">by {{ preset.author }}</a>
			</p>

			<div class="bar">
				<div class="field wide">
					<label class="label" for="heap">Maximum heap</label>
					<input id="heap" v-model="heapInput" class="input" :class="{ bad: !heapValid }" placeholder="8G" />
					<div class="chips">
						<button
							v-for="step in HEAP_STEPS"
							:key="step"
							type="button"
							class="chip"
							:class="{ on: heapInput === step }"
							@click="heapInput = step"
						>
							{{ step }}
						</button>
					</div>
					<p v-if="!heapValid" class="error">Use a size like 8G or 8192M.</p>
				</div>

				<ToolsSegmentedControl
					v-model="java"
					label="Java"
					:options="[
						{ value: '17', label: '17' },
						{ value: '21', label: '21' },
						{ value: '25', label: '25' },
					]"
				/>
				<ToolsSegmentedControl
					v-model="graal"
					label="JVM"
					:options="[
						{ value: 'none', label: 'Any JDK' },
						{ value: 'oracle', label: 'GraalVM' },
					]"
				/>
				<ToolsSegmentedControl
					v-model="os"
					label="Operating system"
					:options="[
						{ value: 'linux', label: 'Linux' },
						{ value: 'windows', label: 'Windows' },
						{ value: 'macos', label: 'macOS' },
					]"
				/>
				<ToolsSegmentedControl
					v-model="arch"
					label="CPU"
					:options="[
						{ value: 'x86_64', label: 'x86_64' },
						{ value: 'aarch64', label: 'ARM64' },
					]"
				/>
			</div>

			<ToolsMoreOptions :hint="optionsHint">
				<div class="bar">
					<div class="field">
						<label class="label" for="jar">Server jar</label>
						<input id="jar" v-model="jar" class="input" placeholder="server.jar" />
					</div>
					<div class="field">
						<label class="label" for="xms">Initial heap</label>
						<input
							id="xms"
							v-model="xmsInput"
							class="input"
							:disabled="xmsLocked"
							:placeholder="xmsLocked ? formatMemMB(heapMB) : '4G'"
						/>
					</div>
					<div class="field">
						<label class="label" for="extra">Extra flags</label>
						<input id="extra" v-model="extra" class="input" placeholder="-Dterminal.jline=false" />
					</div>
				</div>
				<div class="switches">
					<label class="check">
						<input v-model="xmsLocked" type="checkbox" />
						<span>Initial heap equal to maximum</span>
					</label>
					<label class="check">
						<input v-model="proxy" type="checkbox" />
						<span>Proxy, so no <code>--nogui</code></span>
					</label>
					<label class="check">
						<input v-model="restart" type="checkbox" />
						<span>Restart when the server stops</span>
					</label>
				</div>
			</ToolsMoreOptions>
		</section>

		<ToolsCodeOutput v-model:active="activeTab" :tabs="tabs" tall>
			<template #rail>
				<div class="rail-total">
					<strong>{{ presetFlags.length }}</strong> flags, {{ allArgs.length }} arguments
				</div>
			</template>
		</ToolsCodeOutput>

		<div class="meta">
			<span>Java {{ java }}{{ graal === 'oracle' ? ' on Oracle GraalVM' : '' }}, {{ os }}, {{ arch }}</span>
			<span class="grow" />
			<span>Options your JVM would reject are never generated</span>
		</div>

		<div class="under">
			<section class="col">
				<h2>What every flag does</h2>
				<p class="lead">Only the flags in the set above, in the order they are passed.</p>
				<ToolsFlagList :flags="presetFlags" />
			</section>

			<aside class="col">
				<h2>Notes</h2>
				<p class="lead">What the host did to the flag list, and what the set quietly assumes.</p>
				<ToolsNoticeList :notices="notices" />
			</aside>
		</div>
	</ToolsToolPage>
</template>

<style scoped>
.setup {
	padding: 16px;
	margin-bottom: 16px;
	border: 1px solid var(--line);
	border-radius: var(--r-lg);
	background: color-mix(in oklab, var(--bg-1) 88%, transparent);
}

.choice {
	display: flex;
	flex-wrap: wrap;
	gap: 4px;
	padding: 4px;
	background: var(--bg-1);
	border: 1px solid var(--line);
	border-radius: var(--r-md);
}

.choice-btn {
	flex: 1 1 auto;
	min-height: 40px;
	min-width: 44px;
	padding: 0 14px;
	border: 0;
	border-radius: var(--r-sm);
	background: transparent;
	color: var(--dim);
	font: 500 13.5px/1 var(--font-sans);
	cursor: pointer;
	transition: background-color 0.15s, color 0.15s;
}

.choice-btn:hover {
	background: var(--bg-2);
	color: var(--fg-hi);
}

.choice-btn.on {
	background: var(--bg-3);
	color: var(--fg-hi);
	box-shadow: inset 0 0 0 1px color-mix(in oklab, var(--fg) 26%, var(--line));
}

.choice-sum {
	margin: 10px 2px 16px;
	font: 400 13px/1.6 var(--font-sans);
	color: var(--mute);
}

.choice-sum a {
	color: var(--brand);
}

.bar {
	display: grid;
	grid-template-columns: repeat(auto-fit, minmax(190px, 1fr));
	gap: 14px 16px;
	align-items: start;
}

.bar + .switches {
	margin-top: 14px;
}

.field {
	display: flex;
	flex-direction: column;
	gap: 8px;
	min-width: 0;
}

.field.wide {
	grid-column: span 2;
}

.label {
	font: 600 11px/1.4 var(--font-sans);
	text-transform: uppercase;
	letter-spacing: 0.08em;
	color: var(--mute);
}

.input {
	width: 100%;
	min-height: 38px;
	padding: 0 12px;
	border: 1px solid var(--line-2);
	border-radius: var(--r-md);
	background: var(--bg-3);
	color: var(--fg-hi);
	font: 500 13.5px/1 var(--font-mono);
}

.input:focus {
	outline: none;
	border-color: color-mix(in oklab, var(--fg) 45%, var(--line));
}

.input:disabled {
	color: var(--mute);
	cursor: not-allowed;
}

.input.bad {
	border-color: var(--err);
}

.error {
	margin: 0;
	font: 400 12.5px/1.5 var(--font-sans);
	color: var(--warn);
}

.chips {
	display: flex;
	flex-wrap: wrap;
	gap: 4px;
}

.chip {
	min-height: 30px;
	padding: 0 10px;
	border: 1px solid var(--line);
	border-radius: var(--r-full);
	background: transparent;
	color: var(--mute);
	font: 500 12px/1 var(--font-mono);
	cursor: pointer;
	transition: border-color 0.15s, color 0.15s;
}

.chip:hover {
	color: var(--fg-hi);
	border-color: var(--line-2);
}

.chip.on {
	background: var(--bg-3);
	color: var(--fg-hi);
	border-color: color-mix(in oklab, var(--fg) 30%, var(--line));
}

.switches {
	display: grid;
	grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
	gap: 4px 20px;
}

.check {
	display: inline-flex;
	gap: 8px;
	align-items: center;
	font: 400 13px/1.4 var(--font-sans);
	color: var(--dim);
	cursor: pointer;
	min-height: 32px;
}

.check input[type='checkbox'] {
	width: 16px;
	height: 16px;
	accent-color: var(--fg);
}

.check code {
	font: 500 12px/1 var(--font-mono);
	color: var(--fg);
}

.rail-total {
	font: 400 11.5px/1.5 var(--font-sans);
	color: var(--mute);
}

.rail-total strong {
	color: var(--fg);
	font-weight: 600;
}

.meta {
	display: flex;
	gap: 16px;
	flex-wrap: wrap;
	align-items: baseline;
	margin: 12px 2px 0;
	font: 400 12.5px/1.5 var(--font-sans);
	color: var(--mute);
}

.grow {
	flex: 1;
}

.under {
	display: grid;
	grid-template-columns: minmax(0, 1.6fr) minmax(0, 1fr);
	gap: 32px;
	margin-top: 40px;
	align-items: start;
}

.col {
	min-width: 0;
}

.col h2 {
	margin: 0 0 6px;
	font: 700 18px/1.3 var(--font-heading);
	color: var(--fg-hi);
}

.lead {
	margin: 0 0 14px;
	max-width: 68ch;
	font: 400 13.5px/1.6 var(--font-sans);
	color: var(--dim);
}

@media (max-width: 1040px) {
	.under {
		grid-template-columns: minmax(0, 1fr);
	}
}

@media (max-width: 720px) {
	.bar {
		grid-template-columns: 1fr;
		gap: 12px;
	}

	.field.wide {
		grid-column: auto;
	}

	.setup {
		padding: 14px;
	}

	.choice-btn {
		flex: 1 1 40%;
		font-size: 13px;
	}

	.under {
		margin-top: 28px;
	}
}
</style>
