<script setup lang="ts">
import { Download } from '@lucide/vue';
import { computed, ref, watch } from 'vue';
import { syncQuery } from '@/lib/query';
import { build, VERIFIED_AGAINST } from '@/lib/serverconfig/build';
import { SOFTWARE_LABELS, type Software } from '@/lib/serverconfig/files';
import {
  DEFAULT_PROFILE,
  INTENSITIES,
  type Intensity,
  type Profile,
  type ProxyKind,
  SERVER_TYPES,
  type ServerType,
} from '@/lib/serverconfig/profile';
import { downloadZip, type ZipEntry } from '@/lib/zip';

useHead({ title: 'Server config generator' });

const route = useRoute();
const query = route.query;
const asText = (key: string, fallback: string) => (typeof query[key] === 'string' ? (query[key] as string) : fallback);
const asNumber = (key: string, fallback: number) => {
  const parsed = Number.parseInt(asText(key, ''), 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
};

const software = ref<Software>(asText('sw', DEFAULT_PROFILE.software) as Software);
const type = ref<ServerType>(asText('type', DEFAULT_PROFILE.type) as ServerType);
const intensity = ref<Intensity>(asText('level', DEFAULT_PROFILE.intensity) as Intensity);
const players = ref(asNumber('players', DEFAULT_PROFILE.players));
const cores = ref(asNumber('cores', DEFAULT_PROFILE.cores));
const worlds = ref(asText('worlds', DEFAULT_PROFILE.worlds) as Profile['worlds']);
const proxy = ref<ProxyKind>(asText('proxy', DEFAULT_PROFILE.proxy) as ProxyKind);
const offlineMode = ref(asText('offline', '') === '1');
const antiCheat = ref(asText('ac', '') === '1');
const customEntities = ref(asText('custom', '') === '1');
const pregenerated = ref(asText('pregen', '') === '1');
const harden = ref(asText('harden', '1') === '1');

const profile = computed<Profile>(() => ({
  software: software.value,
  type: type.value,
  players: Math.min(Math.max(players.value, 1), 2000),
  worlds: worlds.value,
  cores: Math.min(Math.max(cores.value, 1), 128),
  intensity: intensity.value,
  proxy: proxy.value,
  offlineMode: offlineMode.value,
  antiCheat: antiCheat.value,
  customEntities: customEntities.value,
  pregenerated: pregenerated.value,
  harden: harden.value,
}));

const result = computed(() => build(profile.value));
const activeFile = ref('');
const current = computed(() => result.value.files.find(file => file.file.id === activeFile.value));
const selectedType = computed(() => SERVER_TYPES.find(option => option.id === type.value));
const written = computed(() => result.value.files.filter(file => file.changes.length));

const tabs = computed(() =>
  result.value.files.map(file => ({
    id: file.file.id,
    label: file.file.id,
    badge: file.changes.length,
    filename: file.changes.length ? file.file.id : null,
    code: file.text,
    lang: (file.file.format === 'properties' ? 'properties' : 'yaml') as 'properties' | 'yaml',
    empty: `This profile changes nothing in ${file.file.path}. Leave the file as it ships.`,
  })),
);

const optionsHint = computed(() => {
  const on = [
    offlineMode.value && 'offline mode',
    antiCheat.value && 'anti-cheat',
    customEntities.value && 'custom entities',
    pregenerated.value && 'pregenerated',
    harden.value && 'hardening',
  ].filter(Boolean);
  return on.length ? `${on.length} on: ${on.join(', ')}` : 'offline mode, anti-cheat, ItemsAdder, pregenerated world';
});

function readme(): string {
  const worldLabel = { one: 'One', few: 'A few', many: 'Many' }[worlds.value];
  const proxyLabel = { none: 'No', velocity: 'Velocity', bungeecord: 'BungeeCord' }[proxy.value];
  const answers = (
    [
      ['Software', SOFTWARE_LABELS[software.value]],
      ['Server type', selectedType.value?.name],
      ['How far to go', INTENSITIES.find(level => level.id === intensity.value)?.name],
      ['Players at peak', profile.value.players],
      ['CPU cores', profile.value.cores],
      ['Populated worlds', worldLabel],
      ['Behind a proxy', proxyLabel],
    ] as [string, string | number][]
  )
    .map(([name, value]) => `${name.padEnd(17)}${value}`)
    .join('\n  ');

  const warnings = result.value.notices
    .filter(notice => notice.level === 'warning')
    .map(notice => `  * ${notice.title}\n    ${notice.body}`)
    .join('\n\n');

  return [
    'Server configuration generated by https://bxteam.org/tools/server-config',
    `Verified against Minecraft ${VERIFIED_AGAINST}.`,
    '',
    'ANSWERS',
    `  ${answers}`,
    '',
    'WHAT IS IN HERE',
    '  These are partial files. Every key in them is one that should differ from the',
    '  default for this profile; everything else was deliberately left out. Paper,',
    '  Spigot and Bukkit write their own defaults back into a file the first time the',
    '  server starts, so these can be dropped in as they are.',
    '',
    '  Back up your existing configuration first. If a file already exists on the',
    '  server, merge these keys into it rather than replacing it.',
    '',
    'FILES',
    ...written.value.map(file => `  ${file.file.path.padEnd(34)} ${file.changes.length} keys`),
    '',
    'BEFORE YOU START',
    warnings || '  Nothing needs a manual step for this profile.',
    '',
  ].join('\n');
}

function downloadAll() {
  const entries: ZipEntry[] = written.value.map(file => ({ path: file.file.path, text: file.text }));
  entries.push({ path: 'README.txt', text: readme() });
  downloadZip(`${software.value}-${type.value}-config.zip`, entries);
}

watch(
  [
    software,
    type,
    intensity,
    players,
    cores,
    worlds,
    proxy,
    offlineMode,
    antiCheat,
    customEntities,
    pregenerated,
    harden,
  ],
  () => {
    syncQuery({
      sw: software.value,
      type: type.value,
      level: intensity.value,
      players: String(players.value),
      cores: String(cores.value),
      worlds: worlds.value,
      proxy: proxy.value === 'none' ? undefined : proxy.value,
      offline: offlineMode.value ? '1' : undefined,
      ac: antiCheat.value ? '1' : undefined,
      custom: customEntities.value ? '1' : undefined,
      pregen: pregenerated.value ? '1' : undefined,
      harden: harden.value ? undefined : '0',
    });
  },
  { flush: 'post' },
);

const SOFTWARE_OPTIONS = (['paper', 'purpur', 'divinemc'] as Software[]).map(id => ({
  value: id,
  label: SOFTWARE_LABELS[id],
}));
</script>

<template>
	<ToolsToolPage
		title="Server config generator"
		lead="Say what the server is and what it runs on. You get back the keys that should differ from the defaults, in every config file your server software has, each one carrying the reason it moved. Paths and shipped defaults are read straight out of the upstream sources."
	>
		<section class="setup">
			<div class="choice" role="radiogroup" aria-label="Server type">
				<button
					v-for="option in SERVER_TYPES"
					:key="option.id"
					type="button"
					role="radio"
					:aria-checked="type === option.id"
					class="choice-btn"
					:class="{ on: type === option.id }"
					@click="type = option.id"
				>
					{{ option.name }}
				</button>
			</div>
			<p class="choice-sum">{{ selectedType?.blurb }}</p>

			<div class="bar">
				<ToolsSegmentedControl v-model="software" label="Software" :options="SOFTWARE_OPTIONS" />
				<ToolsSegmentedControl
					v-model="intensity"
					label="How far to go"
					:options="INTENSITIES.map(level => ({ value: level.id, label: level.name, hint: level.blurb }))"
				/>
				<div class="field">
					<label class="label" for="players">Players at peak</label>
					<input id="players" v-model.number="players" class="input" type="number" min="1" max="2000" />
				</div>
				<div class="field">
					<label class="label" for="cores">CPU cores</label>
					<input id="cores" v-model.number="cores" class="input" type="number" min="1" max="128" />
				</div>
				<ToolsSegmentedControl
					v-model="worlds"
					label="Populated worlds"
					:options="[
						{ value: 'one', label: 'One' },
						{ value: 'few', label: 'A few' },
						{ value: 'many', label: 'Many' },
					]"
				/>
				<ToolsSegmentedControl
					v-model="proxy"
					label="Behind a proxy"
					:options="[
						{ value: 'none', label: 'No' },
						{ value: 'velocity', label: 'Velocity' },
						{ value: 'bungeecord', label: 'Bungee' },
					]"
				/>
			</div>

			<ToolsMoreOptions :hint="optionsHint">
				<div class="switches">
					<label class="check">
						<input v-model="offlineMode" type="checkbox" />
						<span>Offline mode, no Mojang authentication</span>
					</label>
					<label class="check">
						<input v-model="antiCheat" type="checkbox" />
						<span>An anti-cheat plugin is installed</span>
					</label>
					<label class="check">
						<input v-model="customEntities" type="checkbox" />
						<span>ItemsAdder, ModelEngine or Oraxen</span>
					</label>
					<label class="check">
						<input v-model="pregenerated" type="checkbox" />
						<span>World is pregenerated with a border</span>
					</label>
					<label class="check">
						<input v-model="harden" type="checkbox" />
						<span>Add packet and item limits</span>
					</label>
				</div>
			</ToolsMoreOptions>
		</section>

		<ToolsCodeOutput v-model:active="activeFile" :tabs="tabs" tall>
			<template #rail>
				<div class="rail-total">
					<strong>{{ result.changed }}</strong> keys in {{ written.length }} files
				</div>
				<button type="button" class="rail-zip" @click="downloadAll">
					<Download :size="13" :stroke-width="1.8" />
					<span>All as .zip</span>
				</button>
			</template>
		</ToolsCodeOutput>

		<div class="meta">
			<span v-if="current">Goes in <code>{{ current.file.path }}</code></span>
			<a v-if="current" :href="current.file.reference" target="_blank" rel="noopener">Reference</a>
			<span class="grow" />
			<span>Verified against Minecraft {{ VERIFIED_AGAINST }}</span>
		</div>

		<div class="under">
			<section v-if="current" class="col">
				<h2>What changed</h2>
				<p class="lead">{{ current.file.blurb }}</p>
				<ToolsChangeList v-if="current.changes.length" :changes="current.changes" />
				<p v-else class="empty">
					Nothing in this file needs to change for this profile. The shipped defaults are already the right answer.
				</p>
			</section>

			<aside class="col">
				<h2>Notes</h2>
				<p class="lead">What the answers above did to the result, and what it quietly assumes.</p>
				<ToolsNoticeList :notices="result.notices" />
			</aside>
		</div>
	</ToolsToolPage>
</template>

<style scoped>
.setup {
	padding: 16px;
	margin-bottom: 16px;
	border: 1px solid var(--line);
	border-radius: var(--r-lg);
	background: color-mix(in oklab, var(--bg-1) 88%, transparent);
}

.choice {
	display: flex;
	flex-wrap: wrap;
	gap: 4px;
	padding: 4px;
	background: var(--bg-1);
	border: 1px solid var(--line);
	border-radius: var(--r-md);
}

.choice-btn {
	flex: 1 1 auto;
	min-height: 40px;
	min-width: 44px;
	padding: 0 14px;
	border: 0;
	border-radius: var(--r-sm);
	background: transparent;
	color: var(--dim);
	font: 500 13.5px/1 var(--font-sans);
	cursor: pointer;
	transition: background-color 0.15s, color 0.15s;
}

.choice-btn:hover {
	background: var(--bg-2);
	color: var(--fg-hi);
}

.choice-btn.on {
	background: var(--bg-3);
	color: var(--fg-hi);
	box-shadow: inset 0 0 0 1px color-mix(in oklab, var(--fg) 26%, var(--line));
}

.choice-sum {
	margin: 10px 2px 16px;
	font: 400 13px/1.6 var(--font-sans);
	color: var(--mute);
}

.bar {
	display: grid;
	grid-template-columns: repeat(auto-fit, minmax(190px, 1fr));
	gap: 14px 16px;
	align-items: start;
}

.field {
	display: flex;
	flex-direction: column;
	gap: 8px;
	min-width: 0;
}

.label {
	font: 600 11px/1.4 var(--font-sans);
	text-transform: uppercase;
	letter-spacing: 0.08em;
	color: var(--mute);
}

.input {
	width: 100%;
	min-height: 38px;
	padding: 0 12px;
	border: 1px solid var(--line-2);
	border-radius: var(--r-md);
	background: var(--bg-3);
	color: var(--fg-hi);
	font: 500 13.5px/1 var(--font-mono);
}

.input:focus {
	outline: none;
	border-color: color-mix(in oklab, var(--fg) 45%, var(--line));
}

.switches {
	display: grid;
	grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
	gap: 4px 20px;
}

.check {
	display: inline-flex;
	gap: 8px;
	align-items: center;
	font: 400 13px/1.4 var(--font-sans);
	color: var(--dim);
	cursor: pointer;
	min-height: 32px;
}

.check input[type='checkbox'] {
	width: 16px;
	height: 16px;
	accent-color: var(--fg);
}

.rail-total {
	margin-bottom: 8px;
	font: 400 11.5px/1.5 var(--font-sans);
	color: var(--mute);
}

.rail-total strong {
	color: var(--fg);
	font-weight: 600;
}

.rail-zip {
	display: inline-flex;
	align-items: center;
	justify-content: center;
	gap: 6px;
	width: 100%;
	min-height: 36px;
	padding: 0 10px;
	border: 1px solid var(--line-2);
	border-radius: var(--r-sm);
	background: var(--bg-2);
	color: var(--dim);
	font: 500 12px/1 var(--font-sans);
	cursor: pointer;
	white-space: nowrap;
}

.rail-zip:hover {
	color: var(--fg-hi);
	border-color: color-mix(in oklab, var(--fg) 30%, var(--line));
}

.meta {
	display: flex;
	gap: 16px;
	flex-wrap: wrap;
	align-items: baseline;
	margin: 12px 2px 0;
	font: 400 12.5px/1.5 var(--font-sans);
	color: var(--mute);
}

.meta code {
	font: 500 12px/1 var(--font-mono);
	color: var(--fg);
}

.meta a {
	color: var(--brand);
}

.grow {
	flex: 1;
}

.under {
	display: grid;
	grid-template-columns: minmax(0, 1.6fr) minmax(0, 1fr);
	gap: 32px;
	margin-top: 40px;
	align-items: start;
}

.col {
	min-width: 0;
}

.col h2 {
	margin: 0 0 6px;
	font: 700 18px/1.3 var(--font-heading);
	color: var(--fg-hi);
}

.lead {
	margin: 0 0 14px;
	max-width: 68ch;
	font: 400 13.5px/1.6 var(--font-sans);
	color: var(--dim);
}

.empty {
	margin: 0;
	padding: 16px;
	border: 1px dashed var(--line-2);
	border-radius: var(--r-lg);
	font: 400 13.5px/1.6 var(--font-sans);
	color: var(--mute);
}

@media (max-width: 1040px) {
	.under {
		grid-template-columns: minmax(0, 1fr);
		gap: 32px;
	}
}

@media (max-width: 720px) {
	.bar {
		grid-template-columns: 1fr;
		gap: 12px;
	}

	.setup {
		padding: 14px;
	}

	.choice-btn {
		flex: 1 1 40%;
		font-size: 13px;
	}

	.under {
		margin-top: 28px;
	}
}

@media (max-width: 860px) {
	.rail-total {
		display: none;
	}
}
</style>
