// Generated by scripts/build-config-reference.ts — do not edit by hand.
// Every default and description below is read out of the upstream source of truth:
// the YAML behind the PaperMC configuration reference, and Purpur's own config classes.
import type { ConfigValue } from './tree';

/** The Minecraft version the sources above were read at. */
export const VERIFIED_AGAINST = '26.2';

export interface ReferenceEntry {
  /** null when upstream has no value for this key by default — an entry in a map that
   *  ships empty, or a default the reference itself only calls "default". */
  default: ConfigValue | null;
  description: string;
}

/** Keyed by `${file}:${path}`. */
export const REFERENCE: Record<string, ReferenceEntry> = {
  'bukkit.yml:chunk-gc.period-in-ticks': {
    default: 600,
    description: 'How long chunks loaded by plugins should last for. Capped by Paper to be 20 ticks (1 second).',
  },
  'bukkit.yml:settings.query-plugins': {
    default: true,
    description: 'Whether to send plugins in the GS4 Query protocol response.',
  },
  'bukkit.yml:spawn-limits.ambient': {
    default: 15,
    description:
      'Set the spawn-limits for ambient mobs. This can be overridden by the [Paper world config](/paper/reference/world-configuration#entities_spawning_spawn_limits_ambient).',
  },
  'bukkit.yml:spawn-limits.animals': {
    default: 10,
    description:
      'Set the spawn-limits for animals. This can be overridden by the [Paper world config](/paper/reference/world-configuration#entities_spawning_spawn_limits_creature).',
  },
  'bukkit.yml:spawn-limits.axolotls': {
    default: 5,
    description:
      'Set the spawn-limits for axolotls. This can be overridden by the [Paper world config](/paper/reference/world-configuration#entities_spawning_spawn_limits_axolotls).',
  },
  'bukkit.yml:spawn-limits.monsters': {
    default: 70,
    description:
      'Set the spawn-limits for monsters. This can be overridden by the [Paper world config](/paper/reference/world-configuration#entities_spawning_spawn_limits_monster).',
  },
  'bukkit.yml:spawn-limits.water-ambient': {
    default: 20,
    description:
      'Set the spawn-limits for water ambient mobs. This can be overridden by the [Paper world config](/paper/reference/world-configuration#entities_spawning_spawn_limits_water_ambient).',
  },
  'bukkit.yml:spawn-limits.water-animals': {
    default: 5,
    description:
      'Set the spawn-limits for water animals. This can be overridden by the [Paper world config](/paper/reference/world-configuration#entities_spawning_spawn_limits_water_creature).',
  },
  'bukkit.yml:spawn-limits.water-underground-creature': {
    default: 5,
    description:
      'Set the spawn-limits for water underground creatures. This can be overridden by the [Paper world config](/paper/reference/world-configuration#entities_spawning_spawn_limits_underground_water_creature).',
  },
  'bukkit.yml:ticks-per.ambient-spawns': {
    default: 1,
    description:
      'Number of ticks between each ambient mob spawn attempt. Set to -1 to use [the Vanilla default](https://minecraft.wiki/w/Mob_spawning#Spawn_cycle). This can be overridden by the [Paper world config](/paper/reference/world-configuration#entities_spawning_ticks_per_spawn_ambient).',
  },
  'bukkit.yml:ticks-per.animal-spawns': {
    default: 400,
    description:
      'Number of ticks between each passive creature (animal) spawn attempt. Set to -1 to use [the Vanilla default](https://minecraft.wiki/w/Mob_spawning#Spawn_cycle). This can be overridden by the [Paper world config](/paper/reference/world-configuration#entities_spawning_ticks_per_spawn_creature).',
  },
  'bukkit.yml:ticks-per.axolotl-spawns': {
    default: 1,
    description:
      'Number of ticks between each axolotl spawn attempt. Set to -1 to use [the Vanilla default](https://minecraft.wiki/w/Mob_spawning#Spawn_cycle). This can be overridden by the [Paper world config](/paper/reference/world-configuration#entities_spawning_ticks_per_spawn_axolotls).',
  },
  'bukkit.yml:ticks-per.monster-spawns': {
    default: 1,
    description:
      'Number of ticks between each hostile monster spawn attempt. Set to -1 to use [the Vanilla default](https://minecraft.wiki/w/Mob_spawning#Spawn_cycle). This can be overridden by the [Paper world config](/paper/reference/world-configuration#entities_spawning_ticks_per_spawn_monster).',
  },
  'bukkit.yml:ticks-per.water-ambient-spawns': {
    default: 1,
    description:
      'Number of ticks between each ambient water mob spawn attempt. Set to -1 to use [the Vanilla default](https://minecraft.wiki/w/Mob_spawning#Spawn_cycle). This can be overridden by the [Paper world config](/paper/reference/world-configuration#entities_spawning_ticks_per_spawn_water_ambient).',
  },
  'bukkit.yml:ticks-per.water-spawns': {
    default: 1,
    description:
      'Number of ticks between each water creature spawn attempt. Set to -1 to use [the Vanilla default](https://minecraft.wiki/w/Mob_spawning#Spawn_cycle). This can be overridden by the [Paper world config](/paper/reference/world-configuration#entities_spawning_ticks_per_spawn_water_creature).',
  },
  'bukkit.yml:ticks-per.water-underground-creature-spawns': {
    default: 1,
    description:
      'Number of ticks between each underground water creatures spawn attempt. Set to -1 to use [the Vanilla default](https://minecraft.wiki/w/Mob_spawning#Spawn_cycle). This can be overridden by the [Paper world config](/paper/reference/world-configuration#entities_spawning_ticks_per_spawn_underground_water_creature).',
  },
  'divinemc.yml:async.chunk-sending.enable': {
    default: false,
    description:
      'Offloads chunk packet serialization to a thread pool, which can significantly reduce main thread load when many players are loading chunks. A consistent snapshot of the chunk is taken on its owning thread, so packets are always internally consistent and packet order is preserved per player.',
  },
  'divinemc.yml:async.chunk-sending.max-threads': { default: 1, description: '' },
  'divinemc.yml:async.parallel-sensors.enable': {
    default: false,
    description:
      "Runs the read-only part of brain AI (sensors: nearest-entity scans, line-of-sight raycasts) on a worker thread pool right before the entity ticking phase, instead of on the main thread during each mob's tick. Sensors are a stable top entry in profiler output on servers with many villagers/piglins, and they only read world state, which makes them safe to batch.",
  },
  'divinemc.yml:async.parallel-world-ticking.enable': {
    default: false,
    description:
      "Enables Parallel World Ticking, which executes each world's tick in a separate thread while ensuring that all worlds complete their tick before the next cycle begins. Read more info about this feature at https://bxteam.org/docs/divinemc/features/parallel-world-ticking",
  },
  'divinemc.yml:async.parallel-world-ticking.thread-count': { default: 4, description: '' },
  'divinemc.yml:async.pathfinding.max-threads': { default: 1, description: '' },
  'divinemc.yml:async.regionized-chunk-ticking.enable': {
    default: false,
    description:
      'Enables regionized chunk ticking, similar to like Folia works. Read more info about this feature at https://bxteam.org/docs/divinemc/features/regionized-chunk-ticking',
  },
  'divinemc.yml:async.regionized-chunk-ticking.executor-thread-count': {
    default: 4,
    description: 'The amount of threads to allocate to regionized chunk ticking.',
  },
  'divinemc.yml:misc.lag-compensation.enabled': {
    default: true,
    description: 'Improves the player experience when TPS is low',
  },
  'divinemc.yml:misc.old-features.copper-bulb-1gt': {
    default: false,
    description: 'Whether to delay the copper lamp by 1 tick when the redstone signal changes.',
  },
  'divinemc.yml:misc.old-features.crafter-1gt': {
    default: false,
    description: 'Whether to reduce the frequency of the crafter outputting items to 1 tick.',
  },
  'divinemc.yml:misc.secure-seed.enable': {
    default: false,
    description:
      'This feature is based on Secure Seed mod by Earthcomputer. Terrain and biome generation remains the same, but all the ores and structures are generated with 1024-bit seed, instead of the usual 64-bit seed. This seed is almost impossible to crack, and there are no weird links between structures.',
  },
  'divinemc.yml:network.general.disable-disconnect-spam': {
    default: false,
    description: "Prevents players being disconnected by 'disconnect.spam' when sending too many chat packets",
  },
  'divinemc.yml:network.no-chat-reports.enabled': {
    default: false,
    description: 'Enables or disables the No Chat Reports feature',
  },
  'divinemc.yml:network.raytrace-entity-culling.enabled': {
    default: false,
    description:
      "Enables Raytrace Entity Culling, a server-side port of tr7zw's EntityCulling mod. Entities that a player provably cannot see (fully hidden behind opaque blocks) are removed from that player's entity tracker. This reduces network bandwidth, improves client FPS and blinds entity-ESP cheats (e.g. freecam/x-ray style hacks cannot see mobs, players or items through walls anymore). Visibility is checked asynchronously via raytracing; when a hidden entity comes into view it is re-tracked within one check interval plus one tracker tick. Players with very high ping may notice entities appearing slightly late when peeking around corners.",
  },
  'divinemc.yml:performance.chunks.chunk-data-cache-limit': { default: 32678, description: '' },
  'divinemc.yml:performance.chunks.chunk-data-cache-soft-limit': { default: 8192, description: '' },
  'divinemc.yml:performance.dab.activation-distance-mod': {
    default: 8,
    description:
      "Modifies an entity's tick frequency. The exact calculation to obtain the tick frequency for an entity is: freq = (distanceToPlayer^2) / (2^value), where value is this configuration setting. Large servers may want to reduce the value to 7, but this value should never be reduced below 6. If you want further away entities to tick more often, set the value to 9",
  },
  'divinemc.yml:performance.dab.enabled': { default: false, description: 'Enables DAB feature' },
  'divinemc.yml:performance.dab.start-distance': {
    default: 12,
    description: 'This value determines how far away an entity has to be',
  },
  'divinemc.yml:performance.optimizations.clump-orbs': {
    default: false,
    description: 'Clumps experience orbs together to reduce entity count',
  },
  'divinemc.yml:performance.optimizations.enable-suffocation-optimization': {
    default: true,
    description:
      'Optimizes the suffocation check by selectively skipping the check in a way that still appears vanilla. This option should be left enabled on most servers, but is provided as a configuration option if the vanilla deviation is undesirable.',
  },
  'divinemc.yml:performance.optimizations.equipment-tracking': {
    default: false,
    description: 'When enabled, skips repeated checks whether the equipment of an entity changed.',
  },
  'divinemc.yml:performance.optimizations.hopper-throttle-when-full.enabled': {
    default: false,
    description: 'When enabled, hoppers will throttle if target container is full.',
  },
  'divinemc.yml:performance.optimizations.hopper-throttle-when-full.skip-ticks': {
    default: 0,
    description: 'The amount of ticks to skip when the hopper is throttled.',
  },
  'divinemc.yml:performance.optimizations.optimized-dragon-respawn': {
    default: false,
    description: 'When enabled, improving performance and reducing lag during the dragon’s resurrection event.',
  },
  'divinemc.yml:performance.optimizations.sleeping-block-entity': {
    default: false,
    description: 'When enabled, block entities will enter a sleep state when they are inactive.',
  },
  'divinemc.yml:performance.optimizations.use-compact-bit-storage': {
    default: false,
    description:
      'Fixes memory waste caused by sending empty chunks as if they contain blocks. Can significantly reduce memory usage.',
  },
  'divinemc.yml:region-settings.thread-count': {
    default: 4,
    description: 'The number of threads to use for IO operations.',
  },
  'divinemc.yml:world-settings.default.unsupported-features.allow-tripwire-dupe': {
    default: false,
    description: 'Bring back MC-59471, MC-129055 on 1.21.2+, which fixed in 1.21.2 snapshots 24w33a and 24w36a',
  },
  'paper-global.yml:item-validation.book-size.page-max': {
    default: 2560,
    description:
      'The max number of bytes a single page in a book can contribute to the allowed byte total for a book, or "disabled" to disable non-vanilla restrictions on the book size.',
  },
  'paper-global.yml:item-validation.book-size.total-multiplier': {
    default: 0.98,
    description:
      'Each page has this multiple of bytes from the last page as its contribution to the allowed byte total for a book (with the first page being having a multiplier of 1.0)',
  },
  'paper-global.yml:item-validation.book.author': {
    default: 8192,
    description: "The maximum length of a book's author in characters",
  },
  'paper-global.yml:item-validation.book.page': {
    default: 16384,
    description: "The maximum length of a book's page in characters",
  },
  'paper-global.yml:item-validation.book.title': {
    default: 8192,
    description: "The maximum length of a book's title in characters",
  },
  'paper-global.yml:item-validation.display-name': {
    default: 8192,
    description: "The maximum length of an item's display name in characters",
  },
  'paper-global.yml:item-validation.lore-line': {
    default: 8192,
    description: 'The maximum length of a lore line in characters',
  },
  'paper-global.yml:item-validation.resolve-selectors-in-books': {
    default: false,
    description:
      'Whether to resolve selectors in books. With this enabled, players given creative mode will be able to crash the server in yet another way',
  },
  'paper-global.yml:misc.max-joins-per-tick': {
    default: 5,
    description:
      'Sets the maximum amount of players that may join the server in a single tick. If more players join, they will be postponed until later ticks to join but not kicked. This is not related to connection throttling found in bukkit.yml',
  },
  'paper-global.yml:packet-limiter.all-packets.action': {
    default: 'KICK',
    description:
      'The action to take once the limit has been violated. Possible values are DROP which will ignore packets over the limit, and KICK which will kick players for exceeding the limit',
  },
  'paper-global.yml:packet-limiter.all-packets.interval': {
    default: 7,
    description: 'The interval, in seconds, for which max-packet-rate should apply',
  },
  'paper-global.yml:packet-limiter.all-packets.max-packet-rate': {
    default: 500,
    description: 'The number of packets allowed per player within the interval',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:command_suggestion.action': {
    default: null,
    description:
      'The action to take once the limit has been violated. Possible values are DROP which will ignore packets over the limit, and KICK which will kick players for exceeding the limit',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:command_suggestion.interval': {
    default: null,
    description: 'The interval, in seconds, for which max-packet-rate should apply',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:command_suggestion.max-packet-rate': {
    default: null,
    description: 'The number of packets allowed per player within the interval',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:container_button_click.action': {
    default: null,
    description:
      'The action to take once the limit has been violated. Possible values are DROP which will ignore packets over the limit, and KICK which will kick players for exceeding the limit',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:container_button_click.interval': {
    default: null,
    description: 'The interval, in seconds, for which max-packet-rate should apply',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:container_button_click.max-packet-rate': {
    default: null,
    description: 'The number of packets allowed per player within the interval',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:container_click.action': {
    default: null,
    description:
      'The action to take once the limit has been violated. Possible values are DROP which will ignore packets over the limit, and KICK which will kick players for exceeding the limit',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:container_click.interval': {
    default: null,
    description: 'The interval, in seconds, for which max-packet-rate should apply',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:container_click.max-packet-rate': {
    default: null,
    description: 'The number of packets allowed per player within the interval',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:custom_payload.action': {
    default: null,
    description:
      'The action to take once the limit has been violated. Possible values are DROP which will ignore packets over the limit, and KICK which will kick players for exceeding the limit',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:custom_payload.interval': {
    default: null,
    description: 'The interval, in seconds, for which max-packet-rate should apply',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:custom_payload.max-packet-rate': {
    default: null,
    description: 'The number of packets allowed per player within the interval',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:interact.action': {
    default: null,
    description:
      'The action to take once the limit has been violated. Possible values are DROP which will ignore packets over the limit, and KICK which will kick players for exceeding the limit',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:interact.interval': {
    default: null,
    description: 'The interval, in seconds, for which max-packet-rate should apply',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:interact.max-packet-rate': {
    default: null,
    description: 'The number of packets allowed per player within the interval',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:place_recipe.action': {
    default: null,
    description:
      'The action to take once the limit has been violated. Possible values are DROP which will ignore packets over the limit, and KICK which will kick players for exceeding the limit',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:place_recipe.interval': {
    default: null,
    description: 'The interval, in seconds, for which max-packet-rate should apply',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:place_recipe.max-packet-rate': {
    default: null,
    description: 'The number of packets allowed per player within the interval',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:player_action.action': {
    default: null,
    description:
      'The action to take once the limit has been violated. Possible values are DROP which will ignore packets over the limit, and KICK which will kick players for exceeding the limit',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:player_action.interval': {
    default: null,
    description: 'The interval, in seconds, for which max-packet-rate should apply',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:player_action.max-packet-rate': {
    default: null,
    description: 'The number of packets allowed per player within the interval',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:set_creative_mode_slot.action': {
    default: null,
    description:
      'The action to take once the limit has been violated. Possible values are DROP which will ignore packets over the limit, and KICK which will kick players for exceeding the limit',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:set_creative_mode_slot.interval': {
    default: null,
    description: 'The interval, in seconds, for which max-packet-rate should apply',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:set_creative_mode_slot.max-packet-rate': {
    default: null,
    description: 'The number of packets allowed per player within the interval',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:use_item_on.action': {
    default: null,
    description:
      'The action to take once the limit has been violated. Possible values are DROP which will ignore packets over the limit, and KICK which will kick players for exceeding the limit',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:use_item_on.interval': {
    default: null,
    description: 'The interval, in seconds, for which max-packet-rate should apply',
  },
  'paper-global.yml:packet-limiter.overrides.minecraft:use_item_on.max-packet-rate': {
    default: null,
    description: 'The number of packets allowed per player within the interval',
  },
  'paper-global.yml:proxies.bungee-cord.online-mode': {
    default: true,
    description:
      "Instructs the server how to handle player UUIDs and data when behind BungeeCord. Always set to match your proxy's online-mode setting",
  },
  'paper-global.yml:proxies.velocity.enabled': {
    default: false,
    description: 'Whether the server should accept Velocity Modern Forwarding',
  },
  'paper-global.yml:proxies.velocity.online-mode': {
    default: true,
    description:
      "Instructs the server how to handle player UUIDs and data when behind Velocity. Always set to match your proxy's online-mode setting",
  },
  'paper-global.yml:unsupported-settings.allow-headless-pistons': {
    default: false,
    description:
      'Whether the server should allow the creation of headless pistons. These are often used to break permanent blocks',
  },
  'paper-global.yml:unsupported-settings.allow-permanent-block-break-exploits': {
    default: false,
    description:
      'Whether unbreakable blocks can be broken with Vanilla exploits. This includes bedrock, end portal frames, end portal blocks, and more',
  },
  'paper-global.yml:unsupported-settings.allow-piston-duplication': {
    default: false,
    description: 'Whether to allow duplication of TNT, carpets, and rails. This does not control sand duplication',
  },
  'paper-world-defaults.yml:anticheat.anti-xray.enabled': {
    default: false,
    description: 'Controls the on/off state for the Anti-Xray system',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.area_effect_cloud': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.arrow': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.breeze_wind_charge': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.dragon_fireball': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.egg': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.ender_pearl': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.experience_bottle': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.experience_orb': {
    default: -1,
    description:
      "Limits the number of experience_orb's that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity.",
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.eye_of_ender': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.fireball': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.firework_rocket': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.lingering_potion': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.llama_spit': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.shulker_bullet': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.small_fireball': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.snowball': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.spectral_arrow': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.splash_potion': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.trident': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.wind_charge': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.entity-per-chunk-save-limit.wither_skull': {
    default: null,
    description:
      'Limits the number of any type of entity that will be saved/loaded per chunk. A value of -1 disables the limit for a specific entity. **Any entity may be added to the list**, beyond the enumerated defaults',
  },
  'paper-world-defaults.yml:chunks.max-auto-save-chunks-per-tick': {
    default: 24,
    description: 'The maximum number of chunks the auto-save system will save in a single tick',
  },
  'paper-world-defaults.yml:chunks.prevent-moving-into-unloaded-chunks': {
    default: false,
    description: 'Sets whether the server will prevent players from moving into unloaded chunks or not',
  },
  'paper-world-defaults.yml:collisions.fix-climbing-bypassing-cramming-rule': {
    default: false,
    description:
      'Sets whether climbing should bypass the entity cramming limit(maxEntityCramming game rule). If set to true, climbing entities will also be counted towards the entity cramming limit so that they can take suffocation damage',
  },
  'paper-world-defaults.yml:collisions.max-entity-collisions': {
    default: 8,
    description: 'Instructs the server to stop processing collisions after this value is reached',
  },
  'paper-world-defaults.yml:entities.armor-stands.do-collision-entity-lookups': {
    default: true,
    description: 'Instructs armor stand entities to do entity collision checks',
  },
  'paper-world-defaults.yml:entities.armor-stands.tick': {
    default: true,
    description: 'Disable to prevent armor stands from ticking. Can improve performance with many armor stands',
  },
  'paper-world-defaults.yml:entities.behavior.disable-chest-cat-detection': {
    default: false,
    description: 'Allows you to open chests even if they have a cat sitting on top of them',
  },
  'paper-world-defaults.yml:entities.behavior.parrots-are-unaffected-by-player-movement': {
    default: false,
    description:
      'Makes parrots "sticky" so they do not fall off a player\'s shoulder when they move. Use crouch to shake them off',
  },
  'paper-world-defaults.yml:entities.behavior.zombies-target-turtle-eggs': {
    default: true,
    description:
      "Sets whether zombies and zombified piglins should target turtle eggs. Setting this to false may help with performance, as they won't search for nearby eggs",
  },
  'paper-world-defaults.yml:entities.markers.tick': {
    default: true,
    description:
      'Disable to prevent markers from ticking. This may affect how they behave as passengers of other entities',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.enabled': {
    default: false,
    description: 'Determines if items will have different despawn rates',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.acacia_leaves': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.andesite': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.bamboo': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.birch_leaves': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.cactus': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.cherry_leaves': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.cobblestone': {
    default: 300,
    description: 'Sets a custom despawn rate for cobblestone of 300 ticks',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.dark_oak_leaves': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.diorite': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.dirt': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.granite': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.gravel': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.jungle_leaves': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.kelp': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.mangrove_leaves': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.melon_slice': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.netherrack': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.oak_leaves': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.pumpkin': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.red_sand': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.sand': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.scaffolding': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.short_grass': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.spruce_leaves': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.sugar_cane': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.twisting_vines': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.alt-item-despawn-rate.items.weeping_vines': {
    default: null,
    description:
      'Determines how long each respective item despawns in ticks. The item ids are the same as those used in the /give command. They can be viewed by enabling advanced item tooltips in-game by pressing **F3 + H**; the item id will appear at the bottom of the tooltip that appears when you hover over an item',
  },
  'paper-world-defaults.yml:entities.spawning.creative-arrow-despawn-rate': {
    default: null,
    description: 'The rate, in ticks, at which arrows shot from players in creative mode are despawned',
  },
  'paper-world-defaults.yml:entities.spawning.despawn-ranges.ambient.hard': {
    default: null,
    description:
      'The horizontal and vertical number of blocks away from a player in which each monster type (set individually) will be forcibly despawned.',
  },
  'paper-world-defaults.yml:entities.spawning.despawn-ranges.ambient.soft': {
    default: null,
    description:
      'The horizontal and vertical number of blocks away from a player in which each monster type (set individually) will be randomly selected to be despawned.',
  },
  'paper-world-defaults.yml:entities.spawning.despawn-ranges.axolotls.hard': {
    default: null,
    description:
      'The horizontal and vertical number of blocks away from a player in which each monster type (set individually) will be forcibly despawned.',
  },
  'paper-world-defaults.yml:entities.spawning.despawn-ranges.axolotls.soft': {
    default: null,
    description:
      'The horizontal and vertical number of blocks away from a player in which each monster type (set individually) will be randomly selected to be despawned.',
  },
  'paper-world-defaults.yml:entities.spawning.despawn-ranges.creature.hard': {
    default: null,
    description:
      'The horizontal and vertical number of blocks away from a player in which each monster type (set individually) will be forcibly despawned.',
  },
  'paper-world-defaults.yml:entities.spawning.despawn-ranges.creature.soft': {
    default: null,
    description:
      'The horizontal and vertical number of blocks away from a player in which each monster type (set individually) will be randomly selected to be despawned.',
  },
  'paper-world-defaults.yml:entities.spawning.despawn-ranges.misc.hard': {
    default: null,
    description:
      'The horizontal and vertical number of blocks away from a player in which each monster type (set individually) will be forcibly despawned.',
  },
  'paper-world-defaults.yml:entities.spawning.despawn-ranges.misc.soft': {
    default: null,
    description:
      'The horizontal and vertical number of blocks away from a player in which each monster type (set individually) will be randomly selected to be despawned.',
  },
  'paper-world-defaults.yml:entities.spawning.despawn-ranges.monster.hard': {
    default: null,
    description:
      'The horizontal and vertical number of blocks away from a player in which each monster type (set individually) will be forcibly despawned.',
  },
  'paper-world-defaults.yml:entities.spawning.despawn-ranges.monster.soft': {
    default: null,
    description:
      'The horizontal and vertical number of blocks away from a player in which each monster type (set individually) will be randomly selected to be despawned.',
  },
  'paper-world-defaults.yml:entities.spawning.despawn-ranges.underground_water_creature.hard': {
    default: null,
    description:
      'The horizontal and vertical number of blocks away from a player in which each monster type (set individually) will be forcibly despawned.',
  },
  'paper-world-defaults.yml:entities.spawning.despawn-ranges.underground_water_creature.soft': {
    default: null,
    description:
      'The horizontal and vertical number of blocks away from a player in which each monster type (set individually) will be randomly selected to be despawned.',
  },
  'paper-world-defaults.yml:entities.spawning.despawn-ranges.water_ambient.hard': {
    default: null,
    description:
      'The horizontal and vertical number of blocks away from a player in which each monster type (set individually) will be forcibly despawned.',
  },
  'paper-world-defaults.yml:entities.spawning.despawn-ranges.water_ambient.soft': {
    default: null,
    description:
      'The horizontal and vertical number of blocks away from a player in which each monster type (set individually) will be randomly selected to be despawned.',
  },
  'paper-world-defaults.yml:entities.spawning.despawn-ranges.water_creature.hard': {
    default: null,
    description:
      'The horizontal and vertical number of blocks away from a player in which each monster type (set individually) will be forcibly despawned.',
  },
  'paper-world-defaults.yml:entities.spawning.despawn-ranges.water_creature.soft': {
    default: null,
    description:
      'The horizontal and vertical number of blocks away from a player in which each monster type (set individually) will be randomly selected to be despawned.',
  },
  'paper-world-defaults.yml:entities.spawning.non-player-arrow-despawn-rate': {
    default: null,
    description:
      'The rate, in ticks, at which arrows shot from non-player entities are despawned. The default value instructs the server to use the same default arrow despawn rate from spigot.yml that is used for all arrows',
  },
  'paper-world-defaults.yml:environment.max-block-ticks': {
    default: 65536,
    description:
      'The maximum number of block ticks that can be processed in a single tick. This is a safety measure to prevent the server from hanging when there is a large amount of block updates.',
  },
  'paper-world-defaults.yml:environment.max-fluid-ticks': {
    default: 65536,
    description:
      'The maximum number of fluid ticks that can be processed in a single tick. This is a safety measure to prevent the server from hanging when there is a large number of fluid updates.',
  },
  'paper-world-defaults.yml:environment.nether-ceiling-void-damage-height': {
    default: null,
    description:
      'Sets the level above which players in the nether will take void damage. This is a Vanilla-friendly way to restrict players from using the nether ceiling as a buildable area. Setting to disabled disables this feature',
  },
  'paper-world-defaults.yml:environment.optimize-explosions': {
    default: false,
    description:
      'Instructs the server to cache entity lookups during an explosion, rather than recalculating throughout the process. This speeds up explosions significantly',
  },
  'paper-world-defaults.yml:environment.treasure-maps.enabled': {
    default: true,
    description: 'If villagers should trade treasure maps and treasure maps from chests should lead to a feature',
  },
  'paper-world-defaults.yml:environment.treasure-maps.find-already-discovered.loot-tables': {
    default: null,
    description:
      'Overrides the loot table-configured check for undiscovered structures. default allows loot tables to individually determine if the map should allow discovered locations in its search. All Vanilla loot tables default to skipping discovered locations so changing this to false would override that behavior and force them to search discovered locations',
  },
  'paper-world-defaults.yml:environment.treasure-maps.find-already-discovered.villager-trade': {
    default: false,
    description:
      'Instructs the server to target the first treasure location found for maps obtained via trading with villagers',
  },
  'paper-world-defaults.yml:fixes.fix-items-merging-through-walls': {
    default: false,
    description:
      'Whether items should be prevented from merging through walls. Enabling this will incur a performance degradation. This is only necessary when merge-radius.item (spigot.yml) is large enough to merge items through walls',
  },
  'paper-world-defaults.yml:hopper.disable-move-event': {
    default: false,
    description:
      'Completely disables the InventoryMoveItemEvent for hoppers. Dramatically improves hopper performance but will break protection plugins and any others that depend on this event',
  },
  'paper-world-defaults.yml:hopper.ignore-occluding-blocks': {
    default: false,
    description:
      'Determines if hoppers will ignore containers inside occluding blocks, like a hopper minecart inside a sand block. Enabling this will improve performance for hoppers checking where to insert items',
  },
  'paper-world-defaults.yml:maps.item-frame-cursor-limit': {
    default: 128,
    description:
      'The number of cursors (markers) allowed per map. A large number of cursors may be used to lag clients',
  },
  'paper-world-defaults.yml:maps.item-frame-cursor-update-interval': {
    default: 10,
    description:
      'The interval in ticks at which cursors on maps in item frames are updated. Setting this to a number less than 1 will disable updates altogether',
  },
  'paper-world-defaults.yml:misc.disable-relative-projectile-velocity': {
    default: false,
    description: 'Instructs the server to ignore shooter velocity when calculating the velocity of a fired arrow',
  },
  'paper-world-defaults.yml:misc.redstone-implementation': {
    default: 'VANILLA',
    description:
      "Specifies the redstone implementation that the server uses. Alternative implementations can greatly reduce the lag caused by redstone dust by optimizing power calculations and reducing the number of block and shape updates emitted. The following implementations are available: - **VANILLA**: The Vanilla redstone implementation. - **EIGENCRAFT**: The Eigencraft redstone implementation by theosib. - **ALTERNATE_CURRENT**: The Alternate Current redstone implementation by Space Walker. **Note:** Both the Eigencraft and Alternate Current implementations change the behavior of redstone dust. You can read about how behavior is changed in each implementation's respective documentation: - Eigencraft: No official documentation available. However, [theosib's comments](https://mojira.dev/MC-81098#comment-id-71035) on the Mojira bug tracker give an overview of the Eigencraft implementation. - [Alternate Current](https://github.com/SpaceWalkerRS/alternate-current/blob/main/README.md)",
  },
  'paper-world-defaults.yml:misc.update-pathfinding-on-block-update': {
    default: true,
    description:
      'Controls whether the pathfinding of mobs is updated when a block is updated in the world. Disabling this option can improve the server performance significantly, while there is almost no noticeable effect on the game mechanics. This is recommended when there are lots of entities loaded, and you have automated farms or redstone clocks',
  },
  'paper-world-defaults.yml:tick-rates.behavior.villager.acquirepoi': {
    default: null,
    description:
      'Sets the behavior tick rate of an entity. -1 uses Vanilla. See timings for the names. Might change between updates!',
  },
  'paper-world-defaults.yml:tick-rates.behavior.villager.validatenearbypoi': {
    default: -1,
    description: 'Sets the tick rate of the validatenearbypoi behavior. of Villager entities',
  },
  'paper-world-defaults.yml:tick-rates.dry-farmland': {
    default: 1,
    description:
      'Controls how frequently dry farmland blocks are ticked. Higher values slow down the rate at which farmland checks for moisture updates. Default (1) uses Vanilla behavior, -1 disables dry farmland random ticks.',
  },
  'paper-world-defaults.yml:tick-rates.grass-spread': {
    default: 1,
    description:
      'Sets the delay, in ticks, at which the server attempts to spread grass. Higher values will result in a slower spread',
  },
  'paper-world-defaults.yml:tick-rates.mob-spawner': {
    default: 1,
    description:
      'How often mob spawners should tick to calculate available spawn areas and spawn new entities into the world. A value of -1 will disable all spawners',
  },
  'paper-world-defaults.yml:tick-rates.sensor.villager.nearestbedsensor': {
    default: null,
    description:
      'Sets the sensor tick rate of an entity. -1 uses Vanilla. See timings for the names. Might change between updates!',
  },
  'paper-world-defaults.yml:tick-rates.sensor.villager.nearestlivingentitysensor': {
    default: null,
    description:
      'Sets the sensor tick rate of an entity. -1 uses Vanilla. See timings for the names. Might change between updates!',
  },
  'paper-world-defaults.yml:tick-rates.sensor.villager.playersensor': {
    default: null,
    description:
      'Sets the sensor tick rate of an entity. -1 uses Vanilla. See timings for the names. Might change between updates!',
  },
  'paper-world-defaults.yml:tick-rates.sensor.villager.secondarypoisensor': {
    default: 40,
    description: 'Sets the tick rate of the secondarypoisensor sensor of Villager entities',
  },
  'paper-world-defaults.yml:tick-rates.sensor.villager.villagerbabiessensor': {
    default: null,
    description:
      'Sets the sensor tick rate of an entity. -1 uses Vanilla. See timings for the names. Might change between updates!',
  },
  'paper-world-defaults.yml:tick-rates.wet-farmland': {
    default: 1,
    description:
      'Controls how frequently wet farmland blocks are ticked. Higher values slow down the rate at which farmland checks for moisture updates. Default (1) uses Vanilla behavior, -1 disables wet farmland random ticks.',
  },
  'purpur.yml:settings.lagging-threshold': {
    default: 19,
    description: 'The TPS below which Purpur considers the server to be lagging.',
  },
  'purpur.yml:settings.logger.suppress-ignored-advancement-warnings': {
    default: false,
    description: 'Hides warnings about advancements the server ignored.',
  },
  'purpur.yml:settings.logger.suppress-init-legacy-material-errors': {
    default: false,
    description: 'Hides the legacy material warnings plugins produce on load.',
  },
  'purpur.yml:settings.logger.suppress-library-loader': {
    default: false,
    description: 'Hides the library loader chatter on startup.',
  },
  'purpur.yml:settings.logger.suppress-setblock-in-far-chunk-errors': {
    default: false,
    description: 'Hides the setblock-in-a-far-chunk errors plugins trigger.',
  },
  'purpur.yml:settings.logger.suppress-unrecognized-recipe-errors': {
    default: false,
    description: 'Hides errors about recipes the server does not recognise.',
  },
  'purpur.yml:settings.use-alternate-keepalive': {
    default: false,
    description:
      'Sends a keepalive packet every second and only kicks after 30 seconds with no answer, instead of kicking on one dropped packet.',
  },
  'purpur.yml:world-settings.default.blocks.observer.disable-clock': {
    default: false,
    description: 'Stops two observers facing each other from producing an endless signal.',
  },
  'purpur.yml:world-settings.default.gameplay-mechanics.armorstand.can-move-in-water': {
    default: true,
    description: 'Whether armour stands are pushed by water.',
  },
  'purpur.yml:world-settings.default.gameplay-mechanics.armorstand.can-move-in-water-over-fence': {
    default: true,
    description: 'Whether armour stands are pushed by water over a fence.',
  },
  'purpur.yml:world-settings.default.gameplay-mechanics.armorstand.can-movement-tick': {
    default: true,
    description: 'Whether armour stands are allowed to move at all.',
  },
  'purpur.yml:world-settings.default.gameplay-mechanics.entities-can-use-portals': {
    default: true,
    description: 'Whether entities other than players may travel through portals.',
  },
  'purpur.yml:world-settings.default.gameplay-mechanics.player.teleport-if-outside-border': {
    default: false,
    description: 'Teleports a player who ends up outside the world border back to spawn.',
  },
  'purpur.yml:world-settings.default.mobs.dolphin.disable-treasure-searching': {
    default: false,
    description: 'Stops dolphins from running the structure search they use to lead players to treasure.',
  },
  'purpur.yml:world-settings.default.mobs.squid.immune-to-EAR': {
    default: true,
    description: 'Whether squid ignore the entity activation range from spigot.yml.',
  },
  'purpur.yml:world-settings.default.mobs.villager.lobotomize.enabled': {
    default: false,
    description: 'A villager that cannot path to its destination loses its AI and only restocks its trades.',
  },
  'purpur.yml:world-settings.default.mobs.villager.search-radius.acquire-poi': {
    default: 'AcquirePoi.SCAN_RANGE',
    description: 'Radius in blocks a villager searches for a job site block.',
  },
  'purpur.yml:world-settings.default.mobs.villager.search-radius.nearest-bed-sensor': {
    default: 'AcquirePoi.SCAN_RANGE',
    description: 'Radius in blocks a villager searches for a bed.',
  },
  'purpur.yml:world-settings.default.mobs.zombie.aggressive-towards-villager-when-lagging': {
    default: true,
    description: 'Whether zombies keep targeting villagers while the server is below the lagging threshold.',
  },
  'server.properties:allow-flight': {
    default: false,
    description:
      'Means that users will not be kicked if they fly whilst in Survival mode. This is likely to occur through hacking however there can be false positives.',
  },
  'server.properties:enforce-secure-profile': {
    default: true,
    description:
      'If set to true, players without a Mojang-signed public key will not be able to connect to the server.',
  },
  'server.properties:entity-broadcast-range-percentage': {
    default: 100,
    description:
      "Controls how close entities need to be before being sent to clients. Higher values means they''ll be rendered from farther away, potentially causing more lag. This is expressed the percentage of the default value. For example, setting to 50 will make it half as usual. This mimics the function on the client video settings (not unlike Render Distance, which the client can customize so long as it''s under the server''s setting). This must be between 10 and 1000 percent.",
  },
  'server.properties:network-compression-threshold': {
    default: 256,
    description: 'The number of bytes of a packet before it is compressed. Setting to a negative disables compression.',
  },
  'server.properties:online-mode': {
    default: true,
    description:
      "If set to true, the server checks all connecting players against Minecraft''s account database. This requires all connected players to have a valid Minecraft account and makes it impossible for cracked players to connect.",
  },
  'server.properties:simulation-distance': {
    default: 10,
    description:
      'Sets the maximum distance from players that living entities may be located in order to be updated by the server, measured in chunks in each direction of the player (radius, not diameter). If entities are outside this radius, then they will not be ticked by the server nor will they be visible to players. Must be between 3 and 32 inclusive.',
  },
  'server.properties:view-distance': {
    default: 10,
    description:
      'Sets the amount of world data the server sends the client, measured in chunks in each direction of the player (radius, not diameter). It determines the server-side viewing distance (Default: 10, Min: 3, Max: 32).',
  },
  'spigot.yml:settings.bungeecord': {
    default: false,
    description:
      'Whether to enable Bungeecord support, enabling: - Receiving forwarded player-data and source ips. - Support for binding to unix domain sockets.',
  },
  'spigot.yml:settings.log-named-deaths': {
    default: true,
    description: 'Whether to log deaths of entities with custom names to console and latest.log',
  },
  'spigot.yml:settings.log-villager-deaths': {
    default: true,
    description: 'Whether to log villager deaths and witch transformations to console and latest.log',
  },
  'spigot.yml:settings.netty-threads': { default: 4, description: 'Sets number of netty threads.' },
  'spigot.yml:settings.save-user-cache-on-stop-only': {
    default: false,
    description: 'If false, the server saves the user-cache on every update.',
  },
  'spigot.yml:world-settings.default.arrow-despawn-rate': {
    default: 1200,
    description: 'The number of ticks before an arrow despawns.',
  },
  'spigot.yml:world-settings.default.entity-activation-range.animals': {
    default: 32,
    description: 'The entity activation range for animals.',
  },
  'spigot.yml:world-settings.default.entity-activation-range.flying-monsters': {
    default: 32,
    description: 'The entity activation range for flying monsters.',
  },
  'spigot.yml:world-settings.default.entity-activation-range.ignore-spectators': {
    default: false,
    description: 'Whether spectators activate entities within range.',
  },
  'spigot.yml:world-settings.default.entity-activation-range.misc': {
    default: 16,
    description:
      'The entity activation range for miscellaneous entities, including dropped items. Outside of this range, items moving through water streams may appear to visually lag, rubber-band, or move backward.',
  },
  'spigot.yml:world-settings.default.entity-activation-range.monsters': {
    default: 32,
    description: 'The entity activation range for monsters.',
  },
  'spigot.yml:world-settings.default.entity-activation-range.raiders': {
    default: 64,
    description: 'The entity activation range for raiders.',
  },
  'spigot.yml:world-settings.default.entity-activation-range.tick-inactive-villagers': {
    default: true,
    description: 'Whether to keep ticking villagers that are outside of their activation range.',
  },
  'spigot.yml:world-settings.default.entity-activation-range.villagers': {
    default: 32,
    description: 'The entity activation range for villagers.',
  },
  'spigot.yml:world-settings.default.entity-activation-range.wake-up-inactive.animals-for': {
    default: 100,
    description: 'How long to wake an inactive animal up for, in ticks.',
  },
  'spigot.yml:world-settings.default.entity-activation-range.wake-up-inactive.animals-max-per-tick': {
    default: 4,
    description: 'A limit of how many inactive animals can be woken up on the same tick.',
  },
  'spigot.yml:world-settings.default.entity-activation-range.wake-up-inactive.flying-monsters-for': {
    default: 100,
    description: 'How long to wake an inactive flying monster up for, in ticks.',
  },
  'spigot.yml:world-settings.default.entity-activation-range.wake-up-inactive.flying-monsters-max-per-tick': {
    default: 8,
    description: 'A limit of how many inactive flying monsters can be woken up on the same tick.',
  },
  'spigot.yml:world-settings.default.entity-activation-range.wake-up-inactive.monsters-for': {
    default: 100,
    description: 'How long to wake an inactive monster up for, in ticks.',
  },
  'spigot.yml:world-settings.default.entity-activation-range.wake-up-inactive.monsters-max-per-tick': {
    default: 8,
    description: 'A limit of how many inactive monsters can be woken up on the same tick.',
  },
  'spigot.yml:world-settings.default.entity-activation-range.wake-up-inactive.villagers-for': {
    default: 100,
    description: 'How long to wake an inactive villager up for, in ticks.',
  },
  'spigot.yml:world-settings.default.entity-activation-range.wake-up-inactive.villagers-max-per-tick': {
    default: 4,
    description: 'A limit of how many inactive villagers can be woken up on the same tick.',
  },
  'spigot.yml:world-settings.default.entity-activation-range.water': {
    default: 16,
    description: 'The entity activation range for water mobs.',
  },
  'spigot.yml:world-settings.default.entity-tracking-range.animals': {
    default: 96,
    description:
      'Controls how far in blocks animals are tracked (sent to) the player. This is scaled by the [entity-broadcast-range-percentage](/paper/reference/server-properties#entity_broadcast_range_percentage).',
  },
  'spigot.yml:world-settings.default.entity-tracking-range.misc': {
    default: 96,
    description:
      'Controls how far in blocks misc entities are tracked (sent to) the player. This is scaled by the [entity-broadcast-range-percentage](/paper/reference/server-properties#entity_broadcast_range_percentage).',
  },
  'spigot.yml:world-settings.default.entity-tracking-range.monsters': {
    default: 96,
    description:
      'Controls how far in blocks monsters are tracked (sent to) the player. This is scaled by the [entity-broadcast-range-percentage](/paper/reference/server-properties#entity_broadcast_range_percentage).',
  },
  'spigot.yml:world-settings.default.entity-tracking-range.other': {
    default: 64,
    description:
      'Controls how far in blocks other entities are tracked (sent to) the player. This is scaled by the [entity-broadcast-range-percentage](/paper/reference/server-properties#entity_broadcast_range_percentage).',
  },
  'spigot.yml:world-settings.default.entity-tracking-range.players': {
    default: 128,
    description:
      'Controls how far in blocks players are tracked (sent to) the player. This is scaled by the [entity-broadcast-range-percentage](/paper/reference/server-properties#entity_broadcast_range_percentage).',
  },
  'spigot.yml:world-settings.default.hanging-tick-frequency': {
    default: 100,
    description: 'How often to tick hanging entities, in ticks.',
  },
  'spigot.yml:world-settings.default.max-tnt-per-tick': {
    default: 100,
    description: 'How many TNT to process per server tick. Set to 0 or less to disable.',
  },
  'spigot.yml:world-settings.default.merge-radius.exp': {
    default: -1,
    description:
      "The range, in blocks, that exp orbs will combine at on initial spawn. This behavior is not present in Vanilla and doesn't impact the usual merge range once spawned. Set to 0 or less to disable.",
  },
  'spigot.yml:world-settings.default.merge-radius.item': {
    default: 0.5,
    description: 'The range, in blocks, that items will combine within.',
  },
  'spigot.yml:world-settings.default.mob-spawn-range': {
    default: 8,
    description: 'The range, in chunks, from the player, that mobs can spawn.',
  },
  'spigot.yml:world-settings.default.nerf-spawner-mobs': {
    default: false,
    description: 'Disable most AI for spawner spawned mobs.',
  },
  'spigot.yml:world-settings.default.ticks-per.hopper-check': {
    default: 1,
    description: 'The ticks between checks to pull items.',
  },
  'spigot.yml:world-settings.default.ticks-per.hopper-transfer': {
    default: 8,
    description: 'The ticks between hopper item movements.',
  },
};

/** Where DivineMC ships a different default than the file it inherits. */
export const DIVINEMC_DELTA: Record<string, ConfigValue> = {
  'bukkit.yml:settings.query-plugins': false,
  'spigot.yml:settings.save-user-cache-on-stop-only': true,
  'purpur.yml:settings.use-alternate-keepalive': true,
};
